### ISSUE TITLE
[devel] sosreport hangs with docker plugin

### ISSUE THREAD

**Issue by bssrikanth** [open-power-host-os/sos#2]
<cde:info> Mirrored with LTC bug https://bugzilla.linux.ibm.com/show_bug.cgi?id=164226 </cde:info>

[root@ltc-wspoon5 ~]# sosreport

sosreport (version 3.4)

This command will collect diagnostic and configuration information from
this CentOS Linux system and installed applications.

An archive containing the collected information will be generated in
/var/tmp/sos.7iLI_T and may be provided to a CentOS support
representative.

Any information provided to CentOS will be treated in accordance with
the published support policies at:

  https://wiki.centos.org/

The generated archive may contain data considered sensitive and its
content should be reviewed by the originating organization before being
passed to any third party.

No changes will be made to system configuration.

Press ENTER to continue, or CTRL-C to quit.

Please enter your first initial and last name [ltc-wspoon5]: 
Please enter the case id that you are generating this report for []: 

 Setting up archive ...
 Setting up plugins ...

 Running plugins. Please wait ...

  Running 16/88: docker...

It hangs in there..

If I disable docker and run.. it just runs fine.

Package levels:

[root@ltc-wspoon5 ~]# uname -r
4.15.0-3.dev.gitd34a158.el7.centos.ppc64le
[root@ltc-wspoon5 ~]# rpm -qa | grep sos
sos-3.4-13.el7.centos.noarch

**Comment by bssrikanth** [comment]
@hegdevasant ^^^ need your inputs

**Comment by cdeadmin** [comment]
------- Comment From seg@us.ibm.com 2018-06-06 12:15:31 EDT-------
Anyone looking at this? Is it still even a problem?

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2018-06-14 06:40:21 EDT-------
Is this still reproducible ? 

-Vasant

**Comment by cdeadmin** [comment]
------- Comment From hegdevasant@in.ibm.com 2018-09-24 11:56:38 EDT-------
Sitting in NEEDINFO for more than 6 months.

REJECTING for now.. Feel free to REOPEN when you have required information.

-Vasant
